### ISSUE TITLE
filebrowser shouldn't require document server URL from the end user

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2396] opened 2021-01-28 12:04 UTC
<img width="1080" alt="Screenshot 2021-01-28 at 13 04 12" src="https://user-images.githubusercontent.com/43240801/106136296-6215fa80-6169-11eb-9106-ef1bd69163d4.png">

**Comment by waleedhammam** [comment] 2021-01-31 11:08
duplicate of: https://github.com/threefoldtech/vdc-solutions-charts/issues/56

**Comment by xmonader** [comment] 2021-02-01 11:38
this is part of 2.5 now not 2.4

**Comment by RafyAmgadBenjamin** [comment] 2021-02-04 13:43
> this is part of 2.5 now not 2.4 @ashraffouda have it disabled please

It has been disabled
#### PR
https://github.com/threefoldtech/js-sdk/pull/2465
#### Branch
development_vdc_filebrowser_disable

**Closed** 2022-11-18 11:23 UTC
Labels: type_question
