### ISSUE TITLE
label all chart resources for backup in chatflow

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#2657] opened 2021-02-28 10:42 UTC
### Description

we need to label all resources that need to be backed up in the chatflow

### Notes:

need to validate all resource related to each chart and override which resources to be labeled. by default (`deployment,rs,svc,sts,ds,cm,secret,ing,pv,pvc,sc`)

**Comment by weynandkuijpers** [comment] 2021-03-15 07:29
Please verify and close or push back to in progress

**Comment by xmonader** [comment] 2021-03-17 07:58
@weynandkuijpers the issue is resolved 16 days ago with PR merged 
![image](https://user-images.githubusercontent.com/64129/111433622-334ae800-8707-11eb-85d9-06212a84d0e7.png)

and its full verification still doesn't have a higher priority for us to spend resources on before actually finishing the milestone.

**Comment by xmonader** [comment] 2021-03-17 08:39
to be continued in https://github.com/threefoldtech/js-sdk/issues/2769

**Closed by xmonader** 2021-03-17 08:39 UTC
Labels: type_feature
