### ISSUE TITLE
when accessing vdc.testnet.grid.tf without tf connect account , i see a blank

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2581] opened 2021-02-19 12:00 UTC
<img width="1440" alt="Screenshot 2021-02-19 at 12 57 32" src="https://user-images.githubusercontent.com/43240801/108501828-28d93200-72b2-11eb-9156-ea3728b50aff.png">

users should see the same homepage of whether or not they have or they don't have a tf connect account.

![deployer](https://user-images.githubusercontent.com/43240801/108501956-52925900-72b2-11eb-8445-87d1ebe0b3d7.png)

**Comment by AhmedSa-mir** [comment] 2021-02-22 12:48
Can't reproduce! I'm redirected to login when accessing [vdc.testnet.grid.tf](https://vdc.testnet.grid.tf/)

![image](https://user-images.githubusercontent.com/18093386/108710565-e8c9b780-751c-11eb-85e4-d79c9632f08a.png)

**Comment by ramezsaeed** [comment] 2021-02-22 13:59
same for me, I'm redirected to login page
![Uploading Screenshot from 2021-02-22 15-58-23.png…]()

**Comment by waleedhammam** [comment] 2021-02-23 13:58
I think the point of the issue is to leave this page unprotected not to redirect to threefold connect in that point

> ![image](https://user-images.githubusercontent.com/10658229/108853624-9efdd180-75ef-11eb-8659-6565aadb0f00.png)

Just like marketplace with login button, and when i click deploy vdc or list my vdcs at this point then redirects to threefold connect if it's not connected

> ![Screenshot from 2021-02-23 15-57-01](https://user-images.githubusercontent.com/10658229/108853774-cce31600-75ef-11eb-90d6-ee501cd28a87.png)

**Comment by sasha-astiadi** [comment] 2021-02-24 15:27
https://user-images.githubusercontent.com/43240801/109023334-fddd4c80-76bc-11eb-8934-c7d5676fc98d.mov

I'm showing you how I get this page,
I logged out. and then I saw the login page. but when I tried to put vdc.testnet.grid.tf it led me to https://vdc.testnet.grid.tf/vdc/#/license
and it went to blank @waleedhammam

**Comment by xmonader** [comment] 2021-02-26 10:05
Let's address this next week

**Comment by sasha-astiadi** [comment] 2021-02-26 10:42
@xmonader moved to2.6

**Comment by AhmedSa-mir** [comment] 2021-02-28 11:14
Problem is after logout we don't clear the cache, so if a user logged out and then clicked the back button he well get into this blank page. Should be fixed by clearing the cache on logout.

**Comment by sasha-astiadi** [comment] 2021-03-03 14:01
still happens to me

**Comment by weynandkuijpers** [comment] 2021-03-15 07:29
Please verify and close or push back to in progress

**Comment by weynandkuijpers** [comment] 2021-03-15 11:43
@sasha-astiadi PLease Verify and close if no longer an issue.

**Comment by waleedhammam** [comment] 2021-03-21 14:52
Can't reproduce, It's caching problem, hard refresh or using incognito mode solves this

**Closed by waleedhammam** 2021-03-21 14:52 UTC
Labels: type_bug
