### ISSUE TITLE
Unable to start threebot server after fresh install

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#1714] opened 2020-11-20 22:35 UTC
After installing a fresh js-sdk (following the instructions on the wiki), I am unable to start a threebot. It keeps failing on the fact that I don't have an identity (and to get one I presumably need to run the threebot first). Passing the `--development` flag, which claims no identity is needed, does not solve the issue.

```
threebot start --local --development
2020-11-20 23:27:38.978 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:93 - jumpscale.core.exceptions.exceptions.Value: No configured identity found
Traceback (most recent call last):
> File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/bin/threebot", line 5, in <module>
    cli()
    └ <Group cli>
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7ff40a282ca0>
           └ <Group cli>
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7ff40b1740a0>
         │    └ <function MultiCommand.invoke at 0x7ff40a283a60>
         └ <Group cli>
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7ff40b203580>
           │               │       │       └ <function Command.invoke at 0x7ff40a283670>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x7ff40b203580>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7ff40b2301f0>
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'local': True, 'development': True, 'identity': None, 'domain': None, 'email': None, 'background': False}
           │   │      │    │           └ <click.core.Context object at 0x7ff40b203580>
           │   │      │    └ <function start at 0x7ff40712d790>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x7ff40a282790>
           └ <click.core.Context object at 0x7ff40b203580>
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'local': True, 'development': True, 'identity': None, 'domain': None, 'email': None, 'background': False}
           │         └ ()
           └ <function start at 0x7ff40712d790>

  File "/home/lee/js-sdk/jumpscale/entry_points/threebot.py", line 86, in start
    create_wallets_if_not_exists()
    └ <function create_wallets_if_not_exists at 0x7ff40712d820>

  File "/home/lee/js-sdk/jumpscale/entry_points/threebot.py", line 277, in create_wallets_if_not_exists
    if not test and "testnet" in j.core.identity.me.explorer_url:
           │                     │ └ <property object at 0x7ff40a288cc0>
           │                     └ <jumpscale.loader.J object at 0x7ff40a27c8b0>
           └ False

  File "/home/lee/js-sdk/jumpscale/core/identity/__init__.py", line 208, in me
    raise Value("No configured identity found")
          └ <class 'jumpscale.core.exceptions.exceptions.Value'>

jumpscale.core.exceptions.exceptions.Value: No configured identity found
```

**Comment by xmonader** [comment] 2020-11-20 23:19
the --development flag is broken for a long time now, as most of the functionality requires an identity, you can easily configure one using this document. created an [issue](https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/identity.md) to remove --development flag

https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/identity.md

**Comment by LeeSmet** [comment] 2020-11-21 00:26
Not passing the `--development` flag led to the same error initially. I did try to comment the function which causes the error, since I don't need a wallet on devnet anyway. And indeed I got an interactive shell, however after filling in the 3bot name and email, I got another error. 

Following the instructions in the linked document and then going back to do a `threebot start --local` now gets the same error (I did do a `threebot clean --all` in between to make sure nothing was left lingering):

```
JS-NG> me = j.core.identity.new(name="default", tname="smetl.3bot", email="lee@threefold.tech", words="<REDACTED>", explorer_url="https://explorer.devnet.grid.tf/api/v1")                     
JS-NG> me.register()                                                                                                   
1627

JS-NG> me.save()                                                                                                       
JS-NG> exit()                                                                                                          

lee on >>=leejaro=>> in js-sdk on  development_public_ip [!] is 📦 v11.1a1 via 🐍 v3.8.6 (js-sdk-4phGcms2-py3.8) took 39s 
🔋89% 🕙[ 01:13:57 ] ❯ threebot start --local
2020-11-21 01:14:02.716 | INFO     | jumpscale.entry_points.threebot:check_for_bins:35 - ✅ binaries nginx,redis-server,tmux,git required are installed.
2020-11-21 01:14:02.822 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:59 - nginx: the configuration file /tmp/tmp9orecp6i syntax is ok
2020-11-21 01:14:02.822 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:59 - 2020/11/21 01:14:02 [emerg] 200447#200447: mkdir() "/var/lib/nginx/client-body" failed (13: Permission denied)
2020-11-21 01:14:02.822 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:59 - nginx: configuration file /tmp/tmp9orecp6i test failed
2020-11-21 01:14:02.847 | INFO     | jumpscale.core.logging.logging:register:141 - Logging from 'jumpscale.servers.gedis' is now bound to 'gedis' app
2020-11-21 01:14:03.199 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:93 - TypeError: 'module' object is not callable
Traceback (most recent call last):
> File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/bin/threebot", line 5, in <module>
    cli()
    └ <Group cli>
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f907acf9ca0>
           └ <Group cli>
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f907bbeb0a0>
         │    └ <function MultiCommand.invoke at 0x7f907acfaa60>
         └ <Group cli>
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f907bc7a580>
           │               │       │       └ <function Command.invoke at 0x7f907acfa670>
           │               │       └ <Command start>
           │               └ <click.core.Context object at 0x7f907bc7a580>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f907bca71f0>
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'local': True, 'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False}
           │   │      │    │           └ <click.core.Context object at 0x7f907bc7a580>
           │   │      │    └ <function start at 0x7f9077ba4af0>
           │   │      └ <Command start>
           │   └ <function Context.invoke at 0x7f907acf9790>
           └ <click.core.Context object at 0x7f907bc7a580>
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'local': True, 'identity': None, 'domain': None, 'email': None, 'development': False, 'background': False}
           │         └ ()
           └ <function start at 0x7f9077ba4af0>

  File "/home/lee/js-sdk/jumpscale/entry_points/threebot.py", line 160, in start
    j.servers.threebot.start_default(wait=True, local=local, domain=domain, email=email)
    │ │                                         │     │      │      │       │     └ None
    │ │                                         │     │      │      │       └ None
    │ │                                         │     │      │      └ None
    │ │                                         │     │      └ None
    │ │                                         │     └ True
    │ │                                         └ True
    │ └ <property object at 0x7f907acffe50>
    └ <jumpscale.loader.J object at 0x7f907acf4880>

  File "/home/lee/js-sdk/jumpscale/servers/threebot/__init__.py", line 34, in start_default
    server.start(wait=wait)
    │      │     │    └ True
    │      │     └ True
    │      └ <function ThreebotServer.start at 0x7f9076bb0ee0>
    └ ThreebotServer(
        instance_name='default',
        _package_manager=StoredFactory(PackageManager),
        domain=None,
        email=None
      )

  File "/home/lee/js-sdk/jumpscale/servers/threebot/threebot.py", line 741, in start
    gevent.signal(signal_type, self.stop)
    │      │      │            │    └ <function ThreebotServer.stop at 0x7f9076bb0f70>
    │      │      │            └ ThreebotServer(
    │      │      │                instance_name='default',
    │      │      │                _package_manager=StoredFactory(PackageManager),
    │      │      │                domain=None,
    │      │      │                email=None
    │      │      │              )
    │      │      └ <Signals.SIGTERM: 15>
    │      └ <module 'gevent.signal' from '/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/gevent/...
    └ <module 'gevent' from '/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/gevent/__init_...

TypeError: 'module' object is not callable
```

**Comment by xmonader** [comment] 2020-11-21 01:32
I don't think you called `j.core.identity.set_default("default")` or `j.core.identity.default.set_default()`, you basically created an identity, but didn't tell the system to use it

**Comment by xmonader** [comment] 2020-11-21 01:50
Actually, I take it back, I can see the instance_name set on the stacktrace.  

the problem is in your gevent version

in 1.4
```
➜  js-sdk git:(development) poetry run jsng
JS-NG> import gevent                                                   
JS-NG> gevent.signal                                                   
<class 'gevent.signal'>

JS-NG> import gevent.signal                                            
JS-NG> type(gevent.signal)                                             
<class 'gevent._signal_metaclass'>

JS-NG> callable(gevent.signal)                                         
True

JS-NG>  
```

in gevent 20

```
In [4]: import gevent.signal                                           

In [5]: type(gevent.signal)                                            
Out[5]: module

In [6]: callable(gevent.signal)                                        
Out[6]: False

In [7]: gevent.version_info                                            
Out[7]: version_info(major=20, minor=0, micro=0, releaselevel='dev', serial=0)
```

**Comment by xmonader** [comment] 2020-12-15 08:46
development flag is fixed, but upgrading gevent version isn't on our plan for this release

**Comment by abom** [comment] 2021-05-10 05:43
Should be resolved by #3003.

**Comment by MElborolossy** [comment] 2021-05-20 15:37
@LeeSmet can you verify after last updates

**Comment by MElborolossy** [comment] 2021-05-20 18:12
Verified
- Create a new venv using `poetry install`
- jsng version: 11.0b13
- gevent: 21.1.2
![image](https://user-images.githubusercontent.com/11272864/119027675-edc8c680-b9a6-11eb-9d22-d78c069d1cf8.png)

- Server Running with development flag
![image](https://user-images.githubusercontent.com/11272864/119027614-d8539c80-b9a6-11eb-9573-fc765e494b3d.png)

**Closed by MElborolossy** 2021-05-20 18:12 UTC
Labels: type_bug
