### ISSUE TITLE
"Create file" in file browser leads to "black" screen

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2367] opened 2021-01-27 10:54 UTC
"Create file" in file browser leads to "black" screen
![image](https://user-images.githubusercontent.com/13766992/105981410-7a294380-60af-11eb-93a0-cd7969565b61.png)

**Comment by waleedhammam** [comment] 2021-01-27 11:00
duplicate of https://github.com/threefoldtech/vdc-solutions-charts/issues/55

**Closed by waleedhammam** 2021-01-27 11:00 UTC
Labels: priority_major, type_bug
