### ISSUE TITLE
needs to say waiting for money

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/js-sdk#544] opened 2020-08-20 10:39 UTC
![image](https://user-images.githubusercontent.com/6021844/90760392-1c175980-e2e2-11ea-86ad-0900e165f6ec.png)

once money there, say money received then do next step

**Comment by rkhamis** [comment] 2020-08-24 10:13
duplicate of #562

**Closed by rkhamis** 2020-08-24 10:13 UTC
