### ISSUE TITLE
3bot deployment : screen #2 new screen: wireguard.

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#824] opened 2020-09-01 09:10 UTC
Title: Install Wireguard

Have you installed a Wireguard VPN? you would need to firstly install a Wireguard VPN on your computer to access the 
network for your 3Bot. Wireguard makes sure that the network connection you're having is fully private and secure.

![photo_2020-09-01_11-13-38](https://user-images.githubusercontent.com/43240801/91831311-3509fe00-ec44-11ea-8893-db5255681db8.jpg)

give them a wireguard download link below, if clicked, it opens on new tab.

**Comment by xmonader** [comment] 2020-09-01 10:14
duplicate of https://github.com/threefoldtech/js-sdk/issues/768

**Closed by xmonader** 2020-09-01 10:14 UTC
