### ISSUE TITLE
can not create a new VDC by vdc.testnet.grid.tf 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/js-sdk#2659] opened 2021-02-28 10:54 UTC
### Description

I have used http://vdc.testnet.grid.tf, payment completed and got the below error while creating the new VDC 
![image](https://user-images.githubusercontent.com/21987477/109415916-15ba1680-79c4-11eb-85b1-672bc4554a7f.png)

**Comment by xmonader** [comment] 2021-03-01 09:58
Caused by signature error. now fixed on testnet deployer.

**Closed by xmonader** 2021-03-01 09:58 UTC
Labels: type_bug
