### ISSUE TITLE
3BOT ADMIN - POOL - #screen 6 review

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#908] opened 2020-09-02 15:12 UTC
<img width="977" alt="Screenshot 2020-09-02 at 17 07 00" src="https://user-images.githubusercontent.com/43240801/92001515-0fadea80-ed3f-11ea-9c78-2d4a95b10f6a.png">

Capacity Pool

Transaction Succeeded
Congratulations! you just created a new capacity pool.

~- [ ] add go to __Capacity Pools__ [link] to see the list of your existing Capacity Pools.~ tracked in another issue.

~- [ ] replace next with 'home'~ -> won't fix now

**Comment by xmonader** [comment] 2020-09-02 19:40
No changes to the buttons of the chatflows framework to be done, I'll limit this issue to the text changes only, the go to feature is duplicate of which is duplicate of https://github.com/threefoldtech/js-sdk/issues/884

**Comment by xmonader** [comment] 2020-09-02 19:44
text changes are fixed in 39f8080c3cfee4b5c2c3789585ae7107e04e84bd

**Closed** 2020-09-03 12:24 UTC
Labels: type_feature
