### ISSUE TITLE
3bot deployment: new user flow

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#812] opened 2020-09-01 08:35 UTC
user flow connect with individual issues:

Old flow:
1. Start
2. solution name
3. [branch name](https://github.com/threefoldtech/js-sdk/issues/805)
4. password
5. expiration time
6. currency
7. pay
8. waiting for payment
9. deploying 
10. Deployment info
10. deploying (waiting again)
11. initializing 3bot (waiting again) -> 
12. wireguard
13. success
14. chat ended

**### New flow:**
1. [Start](https://github.com/threefoldtech/js-sdk/issues/802)
2.[ Install Wireguard.](https://github.com/threefoldtech/js-sdk/issues/824)
Have you installed a wireguard? (explain why it’s needed) 
give them a wireguard download link below, if clicked, it opens on new tab.

3. [Create a new name](https://github.com/threefoldtech/js-sdk/issues/804)
4. [Create a recovery keyd](https://github.com/threefoldtech/js-sdk/issues/807)
5. [Select Expiration time](https://github.com/threefoldtech/js-sdk/issues/815)
6. [Confirm deployment](https://github.com/threefoldtech/js-sdk/issues/814) [ name, password (show button), domain, expiration time)]
7. [Currency](https://github.com/threefoldtech/js-sdk/issues/816)
8. [Pay](https://github.com/threefoldtech/js-sdk/issues/817). if not yet paid, not allowed to go to next step
9. [Deploy](https://github.com/threefoldtech/js-sdk/issues/818)
10. [Wireguard config](https://github.com/threefoldtech/js-sdk/issues/820)
11. [Deployment successful,](https://github.com/threefoldtech/js-sdk/issues/821) go to solution or go back home

other issues / suggestion:

new section for [3bot deployment list](https://github.com/threefoldtech/js-sdk/issues/801) on home

[delete restart button](https://github.com/threefoldtech/js-sdk/issues/808)

**Comment by xmonader** [comment] 2020-09-01 15:30
duplicate of #783

**Closed by xmonader** 2020-09-01 15:30 UTC

**Comment by rkhamis** [comment] 2020-09-02 11:10
moved to #783
