### ISSUE TITLE
Restart a 3bot which ran out of time (finding) results in error

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2316] opened 2021-01-24 09:33 UTC
Restarting an existing 3bot that ran out of gas results in the following error

![image](https://user-images.githubusercontent.com/13766992/105626685-c9226f00-5e4a-11eb-9ce9-03e08fa20df4.png)

3bot name:
mainjetser

**Comment by weynandkuijpers** [comment] 2021-01-24 09:45
Tried two existing (but stopped) 3bots.  Both failed to restart

**Comment by m-motawea** [comment] 2021-01-24 13:29
please add which network. mainnet, testnet, devnet?

**Comment by weynandkuijpers** [comment] 2021-01-24 14:35
testnet - forgot to mention it.

**Comment by m-motawea** [comment] 2021-01-24 14:42
@weynandkuijpers is it a duplicate of https://github.com/threefoldtech/js-sdk/issues/2319? same alert id is shown in both screenshots.

**Closed** 2021-01-24 17:03 UTC
Labels: priority_major, type_bug
