### ISSUE TITLE
TFNow: Taiga deployment is failing on the marketplace

### ISSUE THREAD

**Issue by BenjellounO** [threefoldtech/js-sdk#1506] opened 2020-10-23 16:59 UTC
The Taiga deployment ( from the Taiga widget on the marketplace) is constantly failing.

" failed to deploy workload on node 72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib due to error 402 Client Error: pool needs additional capacity to support this workload for url: https://explorer.testnet.grid.tf/api/v1/reservations/workloads. Please use the refresh button on the upper right to restart the chatflow "

**Comment by m-motawea** [comment] 2020-10-26 07:03
caused by pool https://explorer.testnet.grid.tf/api/v1/reservations/pools/3379 where its `empty_at` value wasn't reset when it expired. probably before it was fixed in the explorer

expired pools have been removed from local config, so you shouldn't face this issue anymore, although you won't be able to deploy atm for same reason as this issue
https://github.com/threefoldtech/js-sdk/issues/1507

**Comment by mhost39** [comment] 2020-11-02 14:16
branch: master
commit: 01f046f672b90adcb3726773bd204b77fb30283c
![image](https://user-images.githubusercontent.com/31102305/97877888-873fcc00-1d26-11eb-9762-ad2b92bf06a9.png)

**Closed by mhost39** 2020-11-02 14:16 UTC
Labels: type_bug
