### ISSUE TITLE
wrong nginx configuration when starting threebot

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#223] opened 2020-07-13 08:19 UTC
os:osx
nginx installed with `brew install nginx`
`threebot start --local`
```
2020-07-13 10:16:18.265 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:38 - nginx: the configuration file /var/folders/75/br_kw5l577zfjlk20fgfqzmr0000gn/T/tmp2hoxuhcy syntax is ok
2020-07-13 10:16:18.266 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:38 - 2020/07/13 10:16:18 [warn] 81643#0: 1024 worker_connections exceed open file resource limit: 256
2020-07-13 10:16:18.266 | DEBUG    | jumpscale.entry_points.threebot:test_privileged_ports_bind:38 - nginx: configuration file /var/folders/75/br_kw5l577zfjlk20fgfqzmr0000gn/T/tmp2hoxuhcy test is successful
2020-07-13 10:16:24.236 | INFO     | jumpscale.core.application.application:start:23 - Application gedis is started, process id: 81641
2020-07-13 10:16:24.247 | INFO     | jumpscale.core.application.application:start:23 - Application threebot_default is started, process id: 81641
2020-07-13 10:16:24.249 | INFO     | jumpscale.servers.threebot.threebot:start:605 - Configuring package auth
2020-07-13 10:16:25.441 | INFO     | jumpscale.servers.threebot.threebot:start:605 - Configuring package chatflows
2020-07-13 10:16:25.485 | INFO     | jumpscale.servers.threebot.threebot:start:605 - Configuring package admin
2020-07-13 10:16:25.791 | INFO     | jumpscale.servers.threebot.threebot:start:605 - Configuring package weblibs
2020-07-13 10:16:25.848 | INFO     | jumpscale.servers.threebot.threebot:start:605 - Configuring package tfgrid_solutions
2020-07-13 10:16:25.962 | INFO     | jumpscale.servers.threebot.threebot:_install_all:483 - Configuring package polls
2020-07-13 10:16:27.501 | ERROR    | jumpscale.sals.nginx.nginx:generate_certificates:176 - Generating certificate failed
Saving debug log to /Users/rob/sandbox/var/log/certbot/letsencrypt.log
Error while running nginx -c /Users/rob/sandbox/cfg/nginx/main/nginx.conf -t.

nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /Users/rob/sandbox/cfg/nginx/main/./default_443/server.conf:2
nginx: configuration file /Users/rob/sandbox/cfg/nginx/main/nginx.conf test failed

The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /Users/rob/sandbox/cfg/nginx/main/nginx.conf -t.\n\nnginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /Users/rob/sandbox/cfg/nginx/main/./default_443/server.conf:2\nnginx: configuration file /Users/rob/sandbox/cfg/nginx/main/nginx.conf test failed\n')

2020-07-13 10:16:28.623 | ERROR    | jumpscale.sals.nginx.nginx:generate_certificates:176 - Generating certificate failed
Saving debug log to /Users/rob/sandbox/var/log/certbot/letsencrypt.log
Error while running nginx -c /Users/rob/sandbox/cfg/nginx/main/nginx.conf -t.

nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /Users/rob/sandbox/cfg/nginx/main/./default_443/server.conf:2
nginx: configuration file /Users/rob/sandbox/cfg/nginx/main/nginx.conf test failed

The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /Users/rob/sandbox/cfg/nginx/main/nginx.conf -t.\n\nnginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /Users/rob/sandbox/cfg/nginx/main/./default_443/server.conf:2\nnginx: configuration file /Users/rob/sandbox/cfg/nginx/main/nginx.conf test failed\n')

2020-07-13 10:16:28.633 | INFO     | jumpscale.servers.threebot.threebot:start:617 - Reloading nginx
2020-07-13 10:16:28.687 | INFO     | jumpscale.servers.threebot.threebot:start:622 - Threebot is running at http://localhost:8080 and https://localhost:8443
```

**Comment by waleedhammam** [comment] 2020-07-13 09:58
ports should be fixed by: https://github.com/threefoldfoundation/tfta-trader/commit/05e6c8c53a1d239db1db575531ca1dc9fbd34df2

**Comment by xmonader** [comment] 2020-07-13 10:22
scenario on how to reproduce: it's caused by having a package defining ports e.g 80, 443 and running threebot with --local

**Comment by RafyAmgadBenjamin** [comment] 2020-07-14 09:41
i will verify this

**Comment by RafyAmgadBenjamin** [comment] 2020-07-14 09:45
#### Verified
#### commit_id 44c902e63830c1298e9bac47bc0f25e699022b7c
![image](https://user-images.githubusercontent.com/46320202/87411028-6876c780-c5c7-11ea-829d-2392151b0787.png)

**Closed** 2020-07-14 18:26 UTC
Labels: priority_major, type_bug
