### ISSUE TITLE
Provide a mechanism to revive the VDC controller in case the node it runs on fails

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2995] opened 2021-04-22 06:50 UTC
FR linked to the bug described in https://github.com/threefoldtech/js-sdk/issues/2965 . 

When a user has reserved a VDC he paid TFTs in advance, plus he has workload running. 
Putting the responsibility entirely with the farmer doesn't work as an end user has paid the VDC provider. So VDC provider should put a mechanism to rebuild the VDC controller in case the node it was running on was down. Or refund the user.

**Comment by AhmedHanafy725** [comment] 2021-04-28 10:27
duplicate of #2989

**Closed by AhmedHanafy725** 2021-04-28 10:27 UTC
Labels: type_feature
