### ISSUE TITLE
Solutions Chatflow have Alert-ID 3 on Testnet VDC

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2334] opened 2021-01-25 11:56 UTC
As part of testing plans , was trying to test the solutions chatflow on testnet VDC Marketplace.

Tested with Peertube , Taiga , i got the following error on mutiple tries :

![image](https://user-images.githubusercontent.com/25789724/105702623-7d90c380-5f25-11eb-9332-02b197ae741e.png)

**Comment by m-motawea** [comment] 2021-01-25 11:58
please add vdc name and owner 3bot name

**Comment by siddiquagig** [comment] 2021-01-25 12:02
VDC name : evdctesnetimp
3bot name : masid

On Testnet

**Comment by m-motawea** [comment] 2021-01-25 12:32
alert content
```python
JS-NG> a.message                                                                                         
'Failed to list charts, error was WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config\nWARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config\nError: Kubernetes cluster unreachable: Get "https://185.69.167.188:6443/version?timeout=32s": dial tcp 185.69.167.188:6443: connect: no route to host\n'

JS-NG> 
```

and I'm unable to reach this ip
```
root@zosv2tst-1:~# kubectl get nodes
Unable to connect to the server: dial tcp 185.69.167.188:6443: connect: no route to host
root@zosv2tst-1:~# 
```

the public ip is deleted https://explorer.testnet.grid.tf/api/v1/reservations/workloads/2889

seems the pool ipv4us have expired and payment timedout in the explorer 


```
log.txt:2021-01-25 09:45:27.059 | INFO     | jumpscale.sals.vdc.deployer:_log:713 - VDC: 05308cb4647c46cf8bf6a0ec36521e90 NAME: evdctesnetimp: OWNER: masid renew plan: extending pool 578, sus: 397980.0000000001, cus: 2110500.0000000005, ipv4us: 1206000.0 reservation_id: 584
```
the payment expired but the code didn't check for the payment result.
https://explorer.testnet.grid.tf/api/v1/reservations/pools/payment/584

will wait for pool payment to be success in the explorer to renew_plan

**Comment by waleedhammam** [comment] 2021-01-25 13:36
verified, can't reproduce
![Screenshot from 2021-01-25 15-36-26](https://user-images.githubusercontent.com/10658229/105712872-1d008700-5f23-11eb-980a-173dff04ffe0.png)

**Comment by siddiquagig** [comment] 2021-01-26 06:47
Having the issue again on all Marketplace Solution Chatflows :  


![image](https://user-images.githubusercontent.com/25789724/105810163-e29af680-5fc3-11eb-94f7-66d0054b660f.png)

**Comment by m-motawea** [comment] 2021-01-26 08:02
> Having the issue again on all Marketplace Solution Chatflows :
> 
> ![image](https://user-images.githubusercontent.com/25789724/105810163-e29af680-5fc3-11eb-94f7-66d0054b660f.png)

of course you still have the issue in this vdc because it's public ip expired. it won't fix itself.

the fix for this issue is in the deployment stage. please deploy a new vdc and if you face the same issue reopen

**Closed by m-motawea** 2021-01-26 08:02 UTC
Labels: type_bug
