### ISSUE TITLE
VDC marketplace: Taiga deployment failed

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2047] opened 2020-12-29 15:12 UTC
Taiga deployment failed from marketplace within my VDC

<img width="910" alt="Screenshot 2020-12-29 at 16 10 33" src="https://user-images.githubusercontent.com/30384423/103293603-7cd14400-49f0-11eb-80bb-d51f08e88c5c.png">

Second try with chosen domain name and with smaller size failed as well:
<img width="910" alt="Screenshot 2020-12-29 at 16 17 23" src="https://user-images.githubusercontent.com/30384423/103294107-78595b00-49f1-11eb-83fd-c3ece79d4643.png">

When I then look into the deployed workloads in marketplace, I see an instance of Taiga, but then when I click on the url itr mentions  "Service unavailable"

<img width="1280" alt="Screenshot 2020-12-29 at 17 17 28" src="https://user-images.githubusercontent.com/30384423/103298058-dd18b380-49f9-11eb-9060-aa5ab562de49.png">

**Comment by OmarElawady** [comment] 2020-12-31 04:27
This is the alert message in the second screen:
```
Failed to deploy chart marketplace/taiga, error was WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "omar" in namespace "default" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "mytaiga2": current value is "mytaiga"
```
it's caused by a misconfiguration in taiga that causes it to reserve a resource with the same name across releases, should be fixed by https://github.com/threefoldtech/js-sdk/pull/2057.

I peeked at the cluster to see the cause of the initialization failure and for some reason the workloads on a specific node was stuck in a crash loop, they get killed, initialized, then killed again by the OOM. This is probably due to deploying expensive pods with not representative requests and no limits.

The node message:
`Warning  SystemOOM  3m25s (x1671 over 19h)  kubelet  (combined from similar events): System OOM encountered, victim process: entry, pid: 27996`

The crashing pods:
```
k3os-system    system-upgrade-controller-6c9f84cb79-248gs        1/1     Running            208        43h                                    
kube-system    metrics-server-7b4f8b595-tkxq7                    0/1     CrashLoopBackOff   207        43h                                    
lens-metrics   node-exporter-vqntn                               0/1     CrashLoopBackOff   205        20h                                    
default        elasticsearch-1609317115-elasticsearch-master-1   0/1     CrashLoopBackOff   236        19h                                    
kube-system    local-path-provisioner-7ff9579c6-qtxpr            1/1     Running            209        43h                                                                                                         
kube-system    coredns-66c464876b-bwsmz                          1/1     Running            206        43h                                                                                                         
kube-system    svclb-traefik-zlcr5                               1/2     CrashLoopBackOff   416        43h                                                                                                         
```

**Comment by waleedhammam** [comment] 2021-01-13 16:42
Verified on vdc.devnet.grid.tf

![Screenshot from 2021-01-13 18-42-05](https://user-images.githubusercontent.com/10658229/104482009-1858dc00-55cf-11eb-8030-b32a6787f825.png)

![Screenshot from 2021-01-13 18-42-18](https://user-images.githubusercontent.com/10658229/104481996-15f68200-55cf-11eb-88db-bf0ca3e86c68.png)

**Closed by waleedhammam** 2021-01-13 16:42 UTC
Labels: type_bug
