### ISSUE TITLE
Deploying a website in the VDC marketplace failed.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2356] opened 2021-01-27 07:38 UTC
While deploying the website chatwizard it failed with the following error:
```
Failed to initialize publishingtools, please contact support with this information: Domain: weynandkuijpers-publishingtools-weynandsweb.webg2test.grid.tf VDC Name: vdc_newvdctoo_weynandkuijpers Farm name: freefarm Reason: Couldn't find resources in the cluster for the solution . Use the refresh button on the upper right to restart Website creation
```
Active workloads:
![image](https://user-images.githubusercontent.com/13766992/105957190-4f7cc200-6092-11eb-84ec-89ceae6cfb5f.png)

Deleted all the existing workloads in the silver VDC so that all the resources would be available in my VDC for this single website (blog).  It did still not deploy.

**Comment by abom** [comment] 2021-01-27 11:07
The first issue is a resources issue, the second one is a duplicate of #2354.

**Comment by rkhamis** [comment] 2021-01-31 20:45
closing because of duplication

**Closed by rkhamis** 2021-01-31 20:45 UTC
Labels: process_duplicate, type_bug
