### ISSUE TITLE
Typo in 3bot deployment

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1586] opened 2020-11-02 10:41 UTC
### Description

![Screenshot 2020-11-01 at 10 48 22](https://user-images.githubusercontent.com/3511318/97859034-4d5bcf00-1d00-11eb-9ad2-3b26d0ad8f8b.png)

**Comment by xmonader** [comment] 2020-12-20 08:44
duplicate of #1826

**Closed** 2020-12-21 11:07 UTC
Labels: type_bug
