### ISSUE TITLE
Deployed document server and it displays an error

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2359] opened 2021-01-27 10:04 UTC
Deployed a document server and the presented URL does not display anything (but an error).

![image](https://user-images.githubusercontent.com/13766992/105975454-67f7d700-60a8-11eb-90aa-7bf6836dc500.png)

![image](https://user-images.githubusercontent.com/13766992/105975501-76de8980-60a8-11eb-89bc-1d4fcc0d9f90.png)

**Comment by weynandkuijpers** [comment] 2021-01-27 10:05
Maybe you cannot access it with a browser, but the the text needs to chenge when the server is deployed.

**Comment by weynandkuijpers** [comment] 2021-01-27 10:07
Filebrowser needs that URL as input -> We need to describe then when document server is deployed.

**Comment by waleedhammam** [comment] 2021-01-27 11:02
duplicate of https://github.com/threefoldtech/vdc-solutions-charts/issues/56

**Closed** 2021-02-01 09:28 UTC
Labels: priority_major, type_bug

**Comment by xmonader** [comment] 2021-02-04 16:33
There won't be a separate deployment of document server
